name: 'CI'
on: ['pull_request', 'push']
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.8.4']
    steps:
    - name: Get info
      id: info
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "::set-output name=path::C:\Users\runneradmin\AppData\Roaming\local\bin"
          echo "::set-output name=cache::C:\Users\runneradmin\AppData\Roaming\stack"
        else
          echo "::set-output name=path::$HOME/.local/bin"
          echo "::set-output name=cache::$HOME/.stack"
        fi

    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ${{ steps.info.outputs.cache }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('fregot.cabal', 'stack.yaml', 'stack.yaml.lock') }}

    - name: Add local/bin to PATH
      shell: bash
      run: echo "::add-path::${{ steps.info.outputs.path }}"

    - name: Build
      run: make install
      id: build

    - name: Test
      run: make test
