name: 'CI'
on: ['pull_request', 'push']
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1.2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-v4

    - name: Add ~/.local/bin to PATH
      run: echo "::add-path::$HOME/.local/bin"

    - name: Build
      run: make install
      id: build

    - name: Test
      run: make test
